---
title: "03_filter_trees_HOLC"
author: "Kelsey McGurrin Dexter H. Locke"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  
## 0 set up: load libraries, custom functions, set defaults
```{r}

# load libraries
# packages we'll be using
packs <- c(
  'tidyverse'         # a must have!
  , 'tidylog'         # makes things very verbose for 2x checking 
  , 'magrittr'        # all of the pipes
  , 'janitor'         # cleans things up
  , 'sf'              # spatial support
  #, 'tidycensus'      # Census access
  , 'mapview'         # webmaps
  , 'tictoc'          # times things
  , 'beepr'           # makes noises
  )         

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

# load them
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)



# keep random things consistent
# set.seed(19870630) # needed?


# redlining colors
holc_pal <- c('#92BC6B' # green
              , '#92C7C9' # blue
              , '#E7DC6B' # yellow
              , '#E47D67' # red
              #, '#A9A9A9'
              ) # dark gray)

holc_pal_f<- c('#92BC6B' # green
              , '#92C7C9' # blue
              , '#E7DC6B' # yellow
              , '#E47D67' # red
              , '#A9A9A9'
              , '#000000')


# set custom function for getting spatial data
see_sf <- function(){
# what's in memory that are sf - spatial features?
keep(eapply(.GlobalEnv, class),      # gets the objects in the global environment
     ~ any(str_detect(., "sf"))) %>% # selects elements with sf in them
    names(.) %>% as.character(.)     # my simple features
}

see_sf() -> sf_in_memory

# what are the spatial references of those SF classes?
mget(sf_in_memory) %>% purrr::map(~st_crs(.x)$epsg) %>% unlist() #%>% View()


# # get file size

# custom function for "Not In"
`%nin%` <- Negate(`%in%`)


# fixes mapview
mapviewOptions(fgb = FALSE)

```


## 1 read in HOLC polygons
```{r}
#define new groups for HOLC
(holc_lu <- 
  tribble(
    ~grade, ~grade_group,
    "A",    "AB",
    "B",    "AB",
    "C",    "C",
    "D",    "D",
    NA,     "industrial"
  ))


#read in shapefile, add new column
(holc <- st_read('output_tables/baci_holc_polygons_2024-02-20.gpkg', as_tibble = TRUE) %>% 
    left_join(holc_lu,by="grade"))

#double check reclassification
holc %>%
  st_drop_geometry() %>%
  tabyl(grade,grade_group)

holc %>% 
  #filter(is.na(grade)) %>% 
  mapview(zcol="grade_group")

```


# 2 get species of trees to focus on
```{r}

species_to_include <- 
  googlesheets4::read_sheet('https://docs.google.com/spreadsheets/d/18K_M4e84m2yl0LYTxfubLhMRby1d5Uoosd1fJShEsH8/edit#gid=1234522482'
                            , sheet = 'Narrowed list')

```



# 3 bring in trees
```{r}

tic(); trees <-
  st_read("G:/Shared drives/Grand Challenges/data/bc_forestry_trees_12232020/bc_forestry_trees_12232020.shp") |> 
  # st_read("/Users/dlocke/evo/AFRI_local/input_data/bc_forestry_trees_12232020/bc_forestry_trees_12232020.shp") |> # Dexter path
  filter(SPP %in% species_to_include$SPP) |> 
  # select() # FIXME drop superfluous columns?
  # TODO filter by stem size
  st_transform(st_crs(holc)) |> 
  st_join(holc |> select(area_id, grade_group), left = TRUE) |> 
  mutate(grade_group = ifelse(is.na(grade_group), 'not classified by HOLC', grade_group)); toc() #takes 3 mins to run

# did that work?
trees |> st_drop_geometry() |> tabyl(grade_group)
trees |> glimpse()
trees |> 
  sample_n(1000) |> 
  mapview(zcol = 'grade_group')
  
  

```



# end



