---
title: "03_summarise_heat"
author: "Kelsey McGurrin Dexter H. Locke"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  
## 0 set up: load libraries, custom functions, set defaults
```{r}

# load libraries
# packages we'll be using
packs <- c(
  'tidyverse'         # a must have!
  , 'tidylog'         # makes things very verbose for 2x checking 
  , 'magrittr'        # all of the pipes
  , 'janitor'         # cleans things up
  , 'sf'              # spatial support
  , 'tidycensus'      # Census access
  , 'mapview'         # webmaps
  , 'tictoc'          # times things
  , 'beepr'           # makes noises
  , 'tigris'          # get census shapefiles
  )         

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

# load them
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)



# keep random things consistent
# set.seed(19870630) # needed?


# redlining colors
holc_pal <- c('#92BC6B' # green
              , '#92C7C9' # blue
              , '#E7DC6B' # yellow
              , '#E47D67' # red
              #, '#A9A9A9'
              ) # dark gray)

holc_pal_f<- c('#92BC6B' # green
              , '#92C7C9' # blue
              , '#E7DC6B' # yellow
              , '#E47D67' # red
              , '#A9A9A9'
              , '#000000')


# set custom function for getting spatial data
see_sf <- function(){
# what's in memory that are sf - spatial features?
keep(eapply(.GlobalEnv, class),      # gets the objects in the global environment
     ~ any(str_detect(., "sf"))) %>% # selects elements with sf in them
    names(.) %>% as.character(.)     # my simple features
}

see_sf() -> sf_in_memory

# what are the spatial references of those SF classes?
mget(sf_in_memory) %>% purrr::map(~st_crs(.x)$epsg) %>% unlist() #%>% View()


# # get file size

# custom function for "Not In"
`%nin%` <- Negate(`%in%`)


# fixes mapview
mapviewOptions(fgb = FALSE)

```


# 1 read in the land cover spatial reference system
```{r}

#(heat <- raster::raster('../grand_challenges_large/baltimore/temperature surfaces/bal_af.tif')) # Dexter path
(heat <- raster::raster('../grand_challenges_large/bal_af.tif')) # Kelsey path

# double checker
heat |> mapview::mapview()

```


# 2 read in HOLC
```{r}

(holc <- st_read('output_tables/baci_holc_polygons_2024-02-20.gpkg', as_tibble = TRUE) |> 
   st_transform(st_crs(heat))
 )

# double check
holc |> mapview()

# do we have a true unique id?
holc |> 
  st_drop_geometry() |> 
  distinct(area_id)

holc |> nrow()

```


# ALTERNATE 2 read in census blocks
```{r}


# tracts <- tracts(state="24",county="Baltimore city", cb=T, resolution = "500k", year = 2022) 

# tigris::blocks(state = 'MD'
#   , county = 'Baltimore City'
#   , year = 2020)
# 
# v20 <- load_variables(2020, "pl", cache = TRUE)
# v20 |> View()
# 
# blocks <-
#   tidycensus::get_decennial(
#     geography = 'block'
#   , state = 'MD'
#   , county = 'Baltimore City'
#   , variables = 'P1_001N'
#   , year = 2020
#   , geometry = TRUE
#   , output = 'wide'
#   , moe_level = 95
#   )



# double check
blocks |> mapview()

# do we have a true unique id?
blocks |> 
  st_drop_geometry() |> 
  distinct(TRACTCE)

blocks |> nrow()

```


# 3 heat in in HOLC via slow but effective for loop
```{r eval=FALSE, include=FALSE}
n_jobs <- 7
shp <-
  holc |>
  tidylog::select(area_id) |>
  mutate(group = santoku::chop_equally(area_id, n_jobs, labels = santoku::lbl_seq(start = 'A'))) 

# checks
all.equal(nrow(shp), shp$area_id |> unique() |> length()) # yes!

# 2x check
shp |> st_drop_geometry() |> tabyl(group)



# kth loop dispatches jobs
# j is just a cheap progress bar
# i is the unique polygon loop
for(k in LETTERS[1:n_jobs]){
  job::job({
    tic()
    j <- 0 # initializes cheap progress bar
    for(i in shp |> filter(group == k) |> distinct(area_id) |> pull(area_id)){

      print(i)             # prints the unique (for troubleshooting)
      j <- j + 1; print(j) # prints the iterator

      # the work horse of the whole operation
      out <-
        terra::crop(heat, shp[shp$area_id == i,]) |>
        terra::mask(shp[shp$area_id == i,]) |>
        terra::values() |>
        mean(na.rm = TRUE)

      # Output is returned as a long-form data frame with a column for plot ID, pixel class, and pixel count.
      # Error catching code is included so that if there are no values in the circle (entirely outside raster)
      data.frame(polygon_id = i, mean_temp_C = as.numeric(out)) |>
        data.table::fwrite(paste0('output_tables/heat_summary_', Sys.Date(), '.csv') # PAY ATTENTION
                           , append = TRUE) # vital!

      }; toc() #; beep() # end ith loop (the individual polygons)
  }) # end job k-th job
  }  # end all ~16 mins w 13 jobs (cores)
```



```{r eval=FALSE, include=FALSE}
# did that work?
(heat_summary <- read_csv('output_tables/heat_summary_2024-02-27.csv') |> 
    rename(area_id = polygon_id))
    

# a double check
heat_summary |> distinct(area_id) |> nrow() - shp |> nrow()
 

# does this join back cleanly?
holc |> 
  left_join(heat_summary, by = 'area_id')

holc |> 
  left_join(heat_summary, by = 'area_id') |> 
  mapview(zcol = 'mean_temp_C')

```


# ALTERNATE 3 heat in census tracts via slow but effective for loop
```{r eval=FALSE, include=FALSE}
n_jobs <- 3
shp <-
  blocks |>
  tidylog::select(TRACTCE) |>
  mutate(group = santoku::chop_equally(TRACTCE, n_jobs, labels = santoku::lbl_seq(start = 'A'))) 

# checks
all.equal(nrow(shp), shp$TRACTCE |> unique() |> length()) # yes!

# 2x check
shp |> st_drop_geometry() |> tabyl(group)



# kth loop dispatches jobs
# j is just a cheap progress bar
# i is the unique polygon loop
for(k in LETTERS[1:n_jobs]){
  job::job({
    tic()
    j <- 0 # initializes cheap progress bar
    for(i in shp |> filter(group == k) |> distinct(TRACTCE) |> pull(TRACTCE)){

      print(i)             # prints the unique (for troubleshooting)
      j <- j + 1; print(j) # prints the iterator

      # the work horse of the whole operation
      out <-
        terra::crop(heat, shp[shp$TRACTCE == i,]) |>
        terra::mask(shp[shp$TRACTCE == i,]) |>
        terra::values() |>
        mean(na.rm = TRUE)

      # Output is returned as a long-form data frame with a column for plot ID, pixel class, and pixel count.
      # Error catching code is included so that if there are no values in the circle (entirely outside raster)
      data.frame(polygon_id = i, mean_temp_C = as.numeric(out)) |>
        data.table::fwrite(paste0('output_tables/heat_summary_', Sys.Date(), '.csv') # PAY ATTENTION
                           , append = TRUE) # vital!

      }; toc() #; beep() # end ith loop (the individual polygons)
  }) # end job k-th job
  }  # end all ~16 mins w 13 jobs (cores)
```

# end



