---
title: "Test Sampling Map"
author: "Kelsey McGurrin Dexter H. Locke"
date: "`r format(Sys.time())`"
output:
  html_document:
    toc: F
    toc_float: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  

```{r include=FALSE}
## 0 set up: load libraries, custom functions, set defaults

# load libraries
# packages we'll be using
packs <- c(
  'tidyverse'         # a must have!
  # , 'tidylog'         # makes things very verbose for 2x checking 
  # , 'magrittr'        # all of the pipes
  # , 'janitor'         # cleans things up
  , 'sf'              # spatial support
  #, 'tidycensus'      # Census access
  , 'mapview'         # webmaps
  # , 'tictoc'          # times things
  # , 'beepr'           # makes noises
  )         

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

# load them
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)



# keep random things consistent
# set.seed(19870630) # needed?


# # redlining colors
# holc_pal <- c('#92BC6B' # green
#               , '#92C7C9' # blue
#               , '#E7DC6B' # yellow
#               , '#E47D67' # red
#               #, '#A9A9A9'
#               ) # dark gray)

# redlining colors
holc_pal_group <- c('#92BC6B' # green
                    , '#92C7C9' # blue
                    , '#E7DC6B' # yellow
                    , '#E47D67' # red
                    #, '#A9A9A9' # dark gray)
                    )

# holc_pal_f<- c('#92BC6B' # green
#               , '#92C7C9' # blue
#               , '#E7DC6B' # yellow
#               , '#E47D67' # red
#               , '#A9A9A9'
#               , '#000000')


# custom function for "Not In"
`%nin%` <- Negate(`%in%`)


# fixes mapview
mapviewOptions(fgb = FALSE)

```


```{r include=FALSE}
## 1 read in HOLC polygons

#define new groups for HOLC
(holc_lu <- 
  tribble(
    ~grade, ~grade_group,
    "A",    "AB",
    "B",    "AB",
    "C",    "C",
    "D",    "D"
    ,    NA,     "industrial"
  ))


#join with shapefile
(holc <- st_read('output_tables/baci_holc_polygons_2024-02-20.gpkg', as_tibble = TRUE) %>% 
    left_join(holc_lu,by="grade") %>%
    select(area_id,geom,grade,grade_group))

```



```{r include=FALSE}
## 2 read in tree data

trees <-  
  st_read('../grand_challenges_large/candidate_street_trees_2024-06-28.gpkg') 


trees$area_id<- replace_na(trees$area_id,0)
trees$grade<- replace_na(trees$grade,"undesignated")

# pull in focal/backup status
sample_list<- 
  googlesheets4::read_sheet('https://docs.google.com/spreadsheets/d/1enawh1zVkaRwxzgn4XSvGy8AOU06hflXeOE778Jl0RU/edit?gid=0#gid=0'
                            , sheet = 'A1-2877') %>%
  select(Burghardt_ID,Status,HOLC_neigh,note_select)

sample_trees <- merge(trees,sample_list)

```


# Map
```{r echo=FALSE, warning=FALSE}
## 3 make maps


sample_trees |>
  mapview(  zcol = 'Status'
          , alpha.regions = .9
          ) +
  mapview( holc, zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade'
          , alpha.regions = .4
          ) 

```

```{r include=FALSE}
## 4 export to google maps

st_write(sample_trees, "sample_trees.kml", driver = "kml",append = F)



```
