---
title: "Baltimore City Neighborhood Maps"
author: "Kelsey McGurrin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/grand challenges git/grand_challenges")
```

```{r include=FALSE}
## 0 set up: load libraries, custom functions, set defaults

# load libraries
# packages we'll be using
packs <- c(
  'tidyverse'         # a must have!
  # , 'tidylog'         # makes things very verbose for 2x checking 
  # , 'magrittr'        # all of the pipes
  # , 'janitor'         # cleans things up
  , 'sf'              # spatial support
  #, 'tidycensus'      # Census access
  , 'mapview'         # webmaps
  # , 'tictoc'          # times things
  # , 'beepr'           # makes noises
  )         

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

# load them
vapply(packs, library, character.only = TRUE, logical(1), logical.return = TRUE, quietly = TRUE)



# redlining colors
holc_pal_group <- c('#92BC6B' # green
                    , '#92C7C9' # blue
                    , '#E7DC6B' # yellow
                    , '#E47D67' # red
                    , '#A9A9A9' # dark gray)
                    )

# tree species colors
spp_colors <- c(
  '#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928'
)

# pest density colors (none, trace, moderate, substantial)
density_colors <- c(
  #'#cbc9e2','#9e9ac8','#756bb1','#54278f' # purples
  #'#cccccc','#969696','#636363','#252525' # grays
  '#fee5d9','#fcae91','#fb6a4a','#cb181d' # reds
  #'#fcae91','#fb6a4a','#de2d26','#a50f15' # darker reds
)

density_grays <- c(
  '#cccccc','#969696','#636363','#252525'
)

density_purples <- c(
  '#cbc9e2','#9e9ac8','#756bb1','#54278f'
)

# custom function for "Not In"
`%nin%` <- Negate(`%in%`)


# fixes mapview
mapviewOptions(fgb = FALSE)

```


```{r include=FALSE}
## 1 read in HOLC polygons

#define new groups for HOLC
(holc_lu <- 
  tribble(
    ~grade, ~grade_group,
    "A",    "AB",
    "B",    "AB",
    "C",    "C",
    "D",    "D"
    ,    NA,     "industrial"
  ))


#join with shapefile
holc <- st_read('output_tables/baci_holc_polygons_2024-02-20.gpkg', as_tibble = TRUE) 

holc <- holc  %>% 
    left_join(holc_lu,by="grade") %>%
    select(area_id,geom,grade,grade_group)

# rename NA grade to industrial
holc$grade[is.na(holc$grade)]<-"industrial"

```


```{r include=FALSE}
## 2 read in heat values for each neighborhood

(heat_summary <- read_csv('output_tables/heat_summary_2024-02-27.csv') |> 
    rename(area_id = polygon_id))

heat_holc <- left_join(holc,heat_summary, by = 'area_id')
```

# Heat across neighborhoods 2018
``` {r include=TRUE, echo= FALSE}
heat_holc |> 
  mapview(
    zcol = 'mean_temp_C'
    , layer.name = 'Mean Temp (C)'
)
```

# HOLC neighborhood grades
``` {r include=TRUE, echo= FALSE}
holc |> 
  mapview(
    zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade'
)
```

``` {r include=FALSE}
# read in summer 2024 data as a shapefile with lat/long
trees <- read_csv("output_tables/GC_cleaned_survey_photosynq_2024.csv")
trees_sf<-st_as_sf(trees,coords = c("long", "lat"), crs = 4326)

```

# All trees sampled summer 2024
``` {r include=TRUE, echo=FALSE}
# trees_sf |> 
#   mapview(zcol = "SPP"
#           , layer.name = 'Tree species'
#           , col.regions = spp_colors
#           )


trees_sf |> 
  mapview(zcol = "SPP"
          , layer.name = 'Tree species'
          , col.regions = "black"
          , alpha.regions = 1
          , legend = F
          , cex = 2
          )+
  mapview( holc,
    zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade')


```

# Liquidambar styraciflua sampled summer 2024
``` {r include=TRUE, echo=FALSE}
trees_sf |> 
  filter(SPP=="Liquidambar styraciflua") |>
  mapview(zcol = "mean_temp_C"
          , layer.name = 'Mean Temperature (C)'
          )

trees_sf |>
  filter(SPP=="Liquidambar styraciflua") |>
  mapview(zcol = "mean_temp_C"
          , layer.name = 'Mean Temperature (C)'
          , alpha.regions = 1
          )+
  mapview( holc, zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade'
          , alpha.regions = .4
  )

```

# Quercus palustris sampled summer 2024
``` {r include=TRUE, echo=FALSE}
trees_sf |> 
  filter(SPP=="Quercus palustris") |>
  mapview(zcol = "mean_temp_C"
          , layer.name = 'Mean Temperature (C)'
          )

trees_sf |>
  filter(SPP=="Quercus palustris") |>
  mapview(zcol = "mean_temp_C"
          , layer.name = 'Mean Temperature (C)'
          , alpha.regions = 1
          )+
  mapview( holc, zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade'
          , alpha.regions = .4
  )

```

# Spotted Lanternfly observed summer 2024
```{r include=TRUE, echo=FALSE}
trees_sf$fac_SLF<-factor(trees_sf$SLF,levels=c("None","Trace","Moderate","Substantive"))


trees_sf |> 
  filter(!is.na(SLF)) |>
  mapview(zcol = "fac_SLF"
          , layer.name = 'SLF density'
          , col.regions = density_purples
          , alpha.regions = 1
          , cex = "fac_SLF"
          )+
  mapview( holc, zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade'
          , alpha.regions = .4
  )


```

# Spotted Lanternfly on Liquidambar styraciflua summer 2024
```{r include=TRUE, echo=FALSE}

trees_sf |> 
  filter(!is.na(SLF)) |>
  filter(SPP=="Liquidambar styraciflua") |>
  mapview(zcol = "fac_SLF"
          , layer.name = 'SLF density'
          , col.regions = density_colors
          , alpha.regions = 1
          ) +
  mapview( holc, zcol = "grade"
          , col.regions = holc_pal_group
          , layer.name = 'HOLC grade'
          , alpha.regions = .4
  )
  

```

# Average SLF per neighborhood summer 2024
```{r include=TRUE, echo=FALSE}
SLF_summary<- trees_sf %>%
  mutate(num_SLF = case_when(`SLF` == "Trace" ~ 1,
                             `SLF` == "Moderate" ~ 2,
                             `SLF` == "Substantive" ~ 3,
                             `SLF` == "None" ~ 0,)) %>%
  group_by(area_id) %>%
  summarize(mean_SLF = mean(num_SLF, na.rm = T))

SLF_summary <- SLF_summary |>
  st_transform(crs = st_crs(holc))

holc_SLF <- st_join(holc,SLF_summary)

holc_SLF |>
  filter(!is.na(mean_SLF)) |>
  mapview(
    zcol = 'mean_SLF'
    , layer.name = 'SLF density'
  )



```

```{r eval=FALSE, include=FALSE}
##### exporting maps to png ##########

# mapshot and mapshot2 not working. webshot works but requires a separate html for each plot 
# (or extensive trial an error selecting the box)
# so far running the mapview() code outside of Rmd so that it appears in Viewer tab and can Export manually

# Heat across neighborhoods 2018

heat_holc |> 
  mapview(
    zcol = 'mean_temp_C'
    , layer.name = 'Mean Temp (C)'
  )

library('webshot2')

m2 <- mapview(heat_holc)
m2
mapshot(m2, file = "heat_holc.png")
mapshot2(m2, file = "heat_holc.png")
webshot(url="file:///C:/Users/kmcgurri/Documents/grand%20challenges%20git/grand_challenges/scripts/07_schaefer_poster_map.html", 
        file = "heat_holc.png"
        , cliprect = "viewport"
        , zoom = 3.5
        )


#### density map of SLF #######

# can convert SLF data to number and bin (already did above, can do finer scales)
# can create density map of tree locations using
# https://www.andrewheiss.com/blog/2023/07/28/gradient-map-fills-r-sf/#fixing-overplotted-scatterplots
# not sure yet how to create density map of SLF

library(spatstat)

#spatstat needs projected CRS 
trees_proj<-st_transform(trees_sf,crs = 3857) 

#get outline of baltimore city
library(tigris)
baci <- counties(state = "24", cb = TRUE, resolution = "500k", year = 2022) %>% 
  filter(NAMELSAD=="Baltimore city") %>%
  st_transform(crs=3857)

# Convert the tree coordinates to a ppp object with a built-in window
trees_ppp <- as.ppp(trees_proj$geometry, W = as.owin(baci))

# Check to see if it worked
plot(trees_ppp)

# Create a stars object of the density of tree locations
density_trees_stars <- stars::st_as_stars(density(trees_ppp, dimyx = 300))

# Check to see what it looks like
plot(density_trees_stars)

# convert back to sf
tree_density <- st_as_sf(density_trees_stars) %>%
  st_set_crs(st_crs(trees_proj))

#plot density along with original points
plot_density <- ggplot() +
  geom_sf(data = tree_density, aes(fill = v), color = NA) +
  geom_sf(data = baci, fill = NA, color = "black", linewidth = 0.25) +
  scale_fill_viridis_c(option = "magma", guide = "none")+
  geom_sf(data = trees_sf, size = 0.3, color = "grey80")
plot_density

```

